// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/anytls/config.proto

package anytls

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account: password-based authentication
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"` // raw password; server computes sha256
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_anytls_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_anytls_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_anytls_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Users []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// optional server padding scheme string
	PaddingScheme string `protobuf:"bytes,2,opt,name=padding_scheme,json=paddingScheme,proto3" json:"padding_scheme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_anytls_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_anytls_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_anytls_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetPaddingScheme() string {
	if x != nil {
		return x.PaddingScheme
	}
	return ""
}

type ClientConfig struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Server        *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"` // 单个服务器地址，不使用列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_anytls_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_anytls_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_anytls_config_proto_rawDescGZIP(), []int{2}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

var File_proxy_anytls_config_proto protoreflect.FileDescriptor

const file_proxy_anytls_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/anytls/config.proto\x12\x11xray.proxy.anytls\x1a\x1acommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\"%\n" +
	"\aAccount\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"g\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12%\n" +
	"\x0epadding_scheme\x18\x02 \x01(\tR\rpaddingScheme\"L\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06serverBU\n" +
	"\x15com.xray.proxy.anytlsP\x01Z&github.com/xtls/xray-core/proxy/anytls\xaa\x02\x11Xray.Proxy.AnyTLSb\x06proto3"

var (
	file_proxy_anytls_config_proto_rawDescOnce sync.Once
	file_proxy_anytls_config_proto_rawDescData []byte
)

func file_proxy_anytls_config_proto_rawDescGZIP() []byte {
	file_proxy_anytls_config_proto_rawDescOnce.Do(func() {
		file_proxy_anytls_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_anytls_config_proto_rawDesc), len(file_proxy_anytls_config_proto_rawDesc)))
	})
	return file_proxy_anytls_config_proto_rawDescData
}

var file_proxy_anytls_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxy_anytls_config_proto_goTypes = []any{
	(*Account)(nil),                 // 0: xray.proxy.anytls.Account
	(*ServerConfig)(nil),            // 1: xray.proxy.anytls.ServerConfig
	(*ClientConfig)(nil),            // 2: xray.proxy.anytls.ClientConfig
	(*protocol.User)(nil),           // 3: xray.common.protocol.User
	(*protocol.ServerEndpoint)(nil), // 4: xray.common.protocol.ServerEndpoint
}
var file_proxy_anytls_config_proto_depIdxs = []int32{
	3, // 0: xray.proxy.anytls.ServerConfig.users:type_name -> xray.common.protocol.User
	4, // 1: xray.proxy.anytls.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_anytls_config_proto_init() }
func file_proxy_anytls_config_proto_init() {
	if File_proxy_anytls_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_anytls_config_proto_rawDesc), len(file_proxy_anytls_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_anytls_config_proto_goTypes,
		DependencyIndexes: file_proxy_anytls_config_proto_depIdxs,
		MessageInfos:      file_proxy_anytls_config_proto_msgTypes,
	}.Build()
	File_proxy_anytls_config_proto = out.File
	file_proxy_anytls_config_proto_goTypes = nil
	file_proxy_anytls_config_proto_depIdxs = nil
}
