// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/tuic/config.proto

package tuic

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account contains user-specific settings for TUIC protocol
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User UUID for authentication
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// User password for authentication
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_tuic_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_tuic_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_tuic_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of server endpoints
	Server []*protocol.ServerEndpoint `protobuf:"bytes,1,rep,name=server,proto3" json:"server,omitempty"`
	// Congestion control algorithm: "cubic", "new_reno", "bbr"
	CongestionControl string `protobuf:"bytes,2,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	// Whether to use UDP stream mode instead of datagram mode
	UdpStream bool `protobuf:"varint,3,opt,name=udp_stream,json=udpStream,proto3" json:"udp_stream,omitempty"`
	// Enable 0-RTT handshake
	ZeroRttHandshake bool `protobuf:"varint,4,opt,name=zero_rtt_handshake,json=zeroRttHandshake,proto3" json:"zero_rtt_handshake,omitempty"`
	// Heartbeat interval in seconds
	Heartbeat     uint32 `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_tuic_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_tuic_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_tuic_config_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfig) GetServer() []*protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ClientConfig) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *ClientConfig) GetUdpStream() bool {
	if x != nil {
		return x.UdpStream
	}
	return false
}

func (x *ClientConfig) GetZeroRttHandshake() bool {
	if x != nil {
		return x.ZeroRttHandshake
	}
	return false
}

func (x *ClientConfig) GetHeartbeat() uint32 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of users with their credentials
	Users []*protocol.User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Congestion control algorithm: "cubic", "new_reno", "bbr"
	CongestionControl string `protobuf:"bytes,2,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	// Authentication timeout in seconds
	AuthTimeout uint32 `protobuf:"varint,3,opt,name=auth_timeout,json=authTimeout,proto3" json:"auth_timeout,omitempty"`
	// Enable 0-RTT handshake
	ZeroRttHandshake bool `protobuf:"varint,4,opt,name=zero_rtt_handshake,json=zeroRttHandshake,proto3" json:"zero_rtt_handshake,omitempty"`
	// Heartbeat interval in seconds
	Heartbeat uint32 `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	// UDP timeout in seconds
	UdpTimeout    uint32 `protobuf:"varint,6,opt,name=udp_timeout,json=udpTimeout,proto3" json:"udp_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_tuic_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_tuic_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_tuic_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *ServerConfig) GetAuthTimeout() uint32 {
	if x != nil {
		return x.AuthTimeout
	}
	return 0
}

func (x *ServerConfig) GetZeroRttHandshake() bool {
	if x != nil {
		return x.ZeroRttHandshake
	}
	return false
}

func (x *ServerConfig) GetHeartbeat() uint32 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *ServerConfig) GetUdpTimeout() uint32 {
	if x != nil {
		return x.UdpTimeout
	}
	return 0
}

var File_proxy_tuic_config_proto protoreflect.FileDescriptor

const file_proxy_tuic_config_proto_rawDesc = "" +
	"\n" +
	"\x17proxy/tuic/config.proto\x12\x0fxray.proxy.tuic\x1a\x1acommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\"9\n" +
	"\aAccount\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xe6\x01\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x03(\v2$.xray.common.protocol.ServerEndpointR\x06server\x12-\n" +
	"\x12congestion_control\x18\x02 \x01(\tR\x11congestionControl\x12\x1d\n" +
	"\n" +
	"udp_stream\x18\x03 \x01(\bR\tudpStream\x12,\n" +
	"\x12zero_rtt_handshake\x18\x04 \x01(\bR\x10zeroRttHandshake\x12\x1c\n" +
	"\theartbeat\x18\x05 \x01(\rR\theartbeat\"\xff\x01\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12-\n" +
	"\x12congestion_control\x18\x02 \x01(\tR\x11congestionControl\x12!\n" +
	"\fauth_timeout\x18\x03 \x01(\rR\vauthTimeout\x12,\n" +
	"\x12zero_rtt_handshake\x18\x04 \x01(\bR\x10zeroRttHandshake\x12\x1c\n" +
	"\theartbeat\x18\x05 \x01(\rR\theartbeat\x12\x1f\n" +
	"\vudp_timeout\x18\x06 \x01(\rR\n" +
	"udpTimeoutBO\n" +
	"\x13com.xray.proxy.tuicP\x01Z$github.com/xtls/xray-core/proxy/tuic\xaa\x02\x0fXray.Proxy.Tuicb\x06proto3"

var (
	file_proxy_tuic_config_proto_rawDescOnce sync.Once
	file_proxy_tuic_config_proto_rawDescData []byte
)

func file_proxy_tuic_config_proto_rawDescGZIP() []byte {
	file_proxy_tuic_config_proto_rawDescOnce.Do(func() {
		file_proxy_tuic_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_tuic_config_proto_rawDesc), len(file_proxy_tuic_config_proto_rawDesc)))
	})
	return file_proxy_tuic_config_proto_rawDescData
}

var file_proxy_tuic_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxy_tuic_config_proto_goTypes = []any{
	(*Account)(nil),                 // 0: xray.proxy.tuic.Account
	(*ClientConfig)(nil),            // 1: xray.proxy.tuic.ClientConfig
	(*ServerConfig)(nil),            // 2: xray.proxy.tuic.ServerConfig
	(*protocol.ServerEndpoint)(nil), // 3: xray.common.protocol.ServerEndpoint
	(*protocol.User)(nil),           // 4: xray.common.protocol.User
}
var file_proxy_tuic_config_proto_depIdxs = []int32{
	3, // 0: xray.proxy.tuic.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	4, // 1: xray.proxy.tuic.ServerConfig.users:type_name -> xray.common.protocol.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_tuic_config_proto_init() }
func file_proxy_tuic_config_proto_init() {
	if File_proxy_tuic_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_tuic_config_proto_rawDesc), len(file_proxy_tuic_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_tuic_config_proto_goTypes,
		DependencyIndexes: file_proxy_tuic_config_proto_depIdxs,
		MessageInfos:      file_proxy_tuic_config_proto_msgTypes,
	}.Build()
	File_proxy_tuic_config_proto = out.File
	file_proxy_tuic_config_proto_goTypes = nil
	file_proxy_tuic_config_proto_depIdxs = nil
}
